import * as d3 from "d3";

export default {
  width: 800,
  height: 500,
  marginTop: 50,
  marginRight: 30,
  marginBottom: 30,
  marginLeft: 60,
  data: [
    {
      date: "24-Apr-07",
      amount: 93.24,
      y2: 0,
      test: "3rdObj1",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "25-Apr-07",
      amount: 95.35,
      y2: 2,
      test: "3rdObj2",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "26-Apr-07",
      amount: 98.84,
      y2: 3,
      test: "3rdObj3",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "27-Apr-07",
      amount: 99.92,
      y2: 1,
      test: "3rdObj4",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "30-Apr-07",
      amount: 99.8,
      y2: 0,
      test: "3rdObj5",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "1-May-07",
      amount: 99.47,
      y2: 1,
      test: "3rdObj6",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "2-May-07",
      amount: 100.39,
      y2: 2,
      test: "3rdObj7",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "3-May-07",
      amount: 100.4,
      y2: 1,
      test: "3rdObj8",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "4-May-07",
      amount: 100.81,
      y2: 1,
      test: "3rdObj9",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "7-May-07",
      amount: 103.92,
      y2: 3,
      test: "3rdObj10",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "8-May-07",
      amount: 105.06,
      y2: 3,
      test: "3rdObj11",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "9-May-07",
      amount: 106.88,
      y2: 0,
      test: "3rdObj12",
      dateAmount: "amount",
      dateY2: "Y2",
    },
    {
      date: "10-May-07",
      amount: 127.34,
      y2: 2,
      test: "3rdObj13",
      dateAmount: "amount",
      dateY2: "Y2",
    },
  ],
  labelY: "amount",
  animation: false,
  valuePosition: 'top',
  fontItalicX: false,
  fontItalicY: true,
  fontWeightX: false,
  fontWeightY: false,
  fontSizeX: 10,
  fontSizeY: 10,
  fontSizeValue: 12,
  fontWeightValues: true,
  fontItalicValues: false,
  rotateXText: 0,
  rotateYText: 0,
  rotateValues: 0,
  limitValue: [10, 20],
  legendSpace: 40,
  sizeLegend: 20,
  ariaFill: true,
  markerSize: 12,
  scaleX: () => d3.scaleTime(),
  scaleY: () => d3.scaleLinear(),
  scaleXName: 'date',
  scaleYName: 'amount',
  schemeCategory: d3.schemeCategory10,
  typeChart: "Line",
};
